
scr = main.c basic_shape.c mouse_op.c print_board.c
para = -Wall

main:$(scr)
	gcc -o main $(scr) $(para)
#all:
	#gcc main.c basic_shape.c -o main
	#./main
clean:
	-rm -rf main
	-rm -rf a.out
	-rm -rf *.o
	-rm -rf *~

